GispoCoding/tarmo

.gitignore, Makefile, README.md
Add .idea and .venv directories to gitignore.
Closes #46.
=> Fix makefile typo, add DB population to readme

web/src/components/Map.tsx, web/yarn.lock
Add geolocation control, aka "locate yourself" button.
Closes #39
=> Add geolocation support

web/src/components/Map.tsx
Toggle fullscreen map and show/hide navigation controls accordingly.
Closes #40
=> Add control to toggle fullscreen

web/package.json, web/src/components/LipasPopup.tsx, web/src/components/Map.tsx, web/src/components/style.ts, web/src/types.ts, web/yarn.lock
This PR:
- Updates maplibre and react-map-gl
- Adds initial popup (without styling)
Relates to #34
=> Add initial popup

.github/workflows/ci.yml, .gitignore, Makefile, README.md, backend/alembic.ini, backend/databasemodel/alembic.ini, backend/databasemodel/alembic/README, backend/databasemodel/alembic/env.py, backend/databasemodel/alembic/script.py.mako, backend/databasemodel/alembic/versions/53986072f514/upgrade.sql, backend/databasemodel/alembic/versions/53986072f514_initial_database_model.py, backend/db_manager.Dockerfile, backend/lambda_functions/db_manager/db_manager.py, backend/test/conftest.py, backend/test/test_db_manager.py, backend/test/test_services.py, requirements.in, requirements.txt
=> Add alembic and tests to db_manager

web/src/components/LayerButton.tsx, web/src/components/LayerPicker.tsx, web/src/components/Map.tsx, web/src/components/style.ts
Adds a basic layer selection menu.
Closes #35
=> Add layer menu

web/src/components/Map.tsx
=> Maintain fullscreen button position

web/src/components/LayerButton.tsx, web/src/components/LayerPicker.tsx
=> Fix LayerPicker functionality

web/src/App.tsx
=> Add placeholder splash screen

web/src/components/InfoButton.tsx, web/src/components/Map.tsx
=> Add placeholder info button

web/src/components/InfoButton.tsx, web/src/components/LayerButton.tsx, web/src/components/LayerPicker.tsx, web/src/main.css, web/src/sass/_components.scss
=> Add styles for info button menu

backend/databasemodel/alembic/versions/ca6838d8e8a5/downgrade.sql, backend/databasemodel/alembic/versions/ca6838d8e8a5/upgrade.sql, backend/databasemodel/alembic/versions/ca6838d8e8a5_adjust_long_lipas_table_names_to_match_.py, backend/databasemodel/model.sql, backend/lambda_functions/lipas_loader/lipas_loader.py, backend/lipas.Dockerfile, backend/test/test_lipas_loader.py, requirements-dev.in, requirements-dev.txt, requirements.in, requirements.txt
=> Add missing lipas data and tests

web/src/App.css, web/src/App.tsx, web/src/components/InfoSlider.tsx, web/src/main.css, web/src/sass/_components.scss
=> 61 add styling for modal slider

web/src/main.css, web/src/sass/_components.scss, web/src/sass/_responsive.scss
=> Fix text overflow

web/src/components/InfoSlider.tsx, web/src/main.css, web/src/sass/_components.scss, web/src/sass/_responsive.scss
=> Add placeholders and responsiveness

web/src/main.css, web/src/sass/_components.scss
=> Fix geolocation color

infra/cloudwatch.tf
Add missing tag for cost management. I did not run terraform yet, can you @Rikuoja do it?
=> Add missing tag

backend/databasemodel/alembic/versions/65bd3f48f528/downgrade.sql, backend/databasemodel/alembic/versions/65bd3f48f528/upgrade.sql, backend/databasemodel/alembic/versions/65bd3f48f528_add_nature_conservation_areas.py, backend/databasemodel/model.sql, backend/test/test_db_manager.py
Add tables for storing nature conservation areas.
=> Luonnonsuojelualueet

web/src/App.tsx, web/src/utils.ts
=> Bugfix map reload issue

web/src/components/InfoSlider.tsx
=> Removed minimize button

web/src/components/InfoSlider.tsx, web/src/utils/UseElementSize.ts
Set correct offset for panel header element
Z-index added to avoid panel going under map controls
=> Reset info slide when content changes

web/src/App.tsx, web/src/components/Map.tsx, web/src/components/SearchMenu.tsx, web/src/index.html, web/src/theme/theme.ts
resolves #189 
The input will still reset on the first time if the user has not moved the map at all. That seems to be caused by another issue.
=> fixed map position

web/src/components/LayerFilter.tsx, web/src/contexts/MapFiltersContext.tsx
Indicator that filters are active
=> Filters stored to local storage

backend/databasemodel/alembic/versions/3df1bb2d0c9b/downgrade.sql, backend/databasemodel/alembic/versions/3df1bb2d0c9b/upgrade.sql, backend/databasemodel/alembic/versions/3df1bb2d0c9b_add_table_name_to_cluster_layers.py, backend/databasemodel/model.sql, web/src/components/InfoSlider.tsx, web/src/components/Map.tsx, web/src/types.ts
=> Display data source when clicking anything

backend/lambda_functions/lipas_loader/lipas_loader.py, backend/test/test_services.py, infra/lambda.tf
Changed python runtime in lambda.tf from 3.8 to 3.10. Cleaned up lipas_loader.py code.
=> Fix lambdas.

licenses.md
Fixed a very small typo and this time making the PR to the right branch.
=> Fix typo in licenses.md
